# -*- coding: utf-8 -*-
from . import appointment_product
from . import appointment_sale_answer_input
from . import fsm_task_answer
from . import product_service_flag
from . import fsm_task_service_line
from . import project_task_signature_wizard
from . import fsm_task_form_line
from . import project_task_stock_receipt
from . import project_task_misc_fields
from . import stock_move_line_field_code
from . import stock_picking_task_link
from . import sale_order_task_nav
from . import res_config_settings
from . import stock_picking_signature
from . import report_print_log
from . import project_task_signatures
from . import quality_check_lab_code
from . import sale_order_task_samples
from . import sale_order_project_columns
from . import stock_picking_lab_notify
from . import project_task_attachments
from . import sale_order_sample_pricing
