# -*- coding: utf-8 -*-
{
    'name': "المواعيد والخدمات الميدانية المتقدمة",
    'summary': "نظام شامل لإدارة مهام الخدمة الميدانية والمختبرات مع ربط المنتجات بالمواعيد",
    'description': "نظام مواعيد وخدمات ميدانية مع فحوصات مختبرية ديناميكية.",
    'author': "المهندس / صالح الحجاني",
    'website': "https://www.facebook.com/salh.alhjany/?rdid=plWVCqF0AkDERe3g",
    'category': 'Services/Appointments',
    'version': '18.0.1.0.8',
    'depends': [
        'appointment', 
        'product', 
        'website_appointment', 
        'website_sale', 
        'website_sale_stock', 
        'web', 
        'sale_management', 
        'phone_validation', 
        'industry_fsm', 
        'industry_fsm_sale', 
        'industry_fsm_report', 
        'stock', 
        'quality',
        'quality_control', 
        'sale_project',
        'timer',
        'mail',
        'base_automation'
    ],
    'data': [

        'security/lab_groups.xml',
        'security/lab_record_rules.xml',
        'security/ir.model.access.csv',
        'security/task_attachment_rules.xml',
        'data/fsm_task_sequence.xml',
        'data/stock_picking_lab_actions.xml',
        'data/brick_test_templates.xml',
        'views/appointment_product_views.xml',
        'views/appointment_products_templates.xml',
        'views/project_task_signature_views.xml',
        'views/sale_order_question_views.xml',
        'views/portal_task_extra_views.xml',
        'views/product_template_service_views.xml',
        'views/project_task_form_views.xml',
        'views/project_task_stock_done_views.xml',
        'views/report_task_extra_views.xml',
        'views/appointment_config_settings_views.xml',
        'views/stock_move_line_views.xml',
        'views/project_task_buttons.xml',
        'views/stock_picking_buttons.xml',
        'views/stock_picking_lab_notify_views.xml',
        'views/sale_order_buttons.xml',
        'views/stock_picking_report_custom.xml',
        'views/stock_picking_signature_views.xml',
        'views/stock_move_line_signature_views.xml',
        'views/project_task_extra_signatures_views.xml',
        'views/product_labels_simple_enhancement.xml',
        'views/sample_product_config_views.xml',
        'views/sale_order_views_inherit_project_name.xml',
        'views/project_task_attachments_views.xml',
        'views/task_attachment_wizard_views.xml',
        'views/product_subtype_test_plan_wizard_views.xml',
        'views/lab_test_template_views.xml',
        'views/lab_test_criterion_views.xml',
        'views/lab_result_set_views.xml',
        'views/lab_result_signature_views.xml',
        'views/sample_type_views.xml',
        'views/lab_menus.xml',
        'views/quality_lab_integration_views.xml',
        'views/lab_result_dynamic_input_views.xml',
        'views/lab_test_flow_views.xml',
        'views/lab_sample_rule_views.xml',
        'views/lab_sample_views.xml',
        'views/stock_picking_sampling_views.xml',
        'data/lab_sample_sequence.xml',
        'data/lab_result_set_sequence.xml',
        'data/lab_test_flow_sequence.xml',
        'data/lab_sample_rule_data.xml',
        #'data/lab_performance_cron.xml',
        'data/lab_notifications.xml',
        #'views/lab_dashboard_views.xml',
        'data/ir_sequence_data.xml',
        'views/sample_cube_views.xml',
        'views/lab_sample_comprehensive_report_views.xml',
        'reports/lab_sample_comprehensive_report.xml',

        'data/dynamic_lab_report_actions.xml',
        'views/dynamic_lab_results_template.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            ('include', 'web._assets_helpers'),
            ('include', 'web._assets_frontend_helpers'),
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/jquery/jquery.js',
            'appointment_products/static/src/js/appointment_products.js',
            'appointment_products/static/src/js/appointment_cart.js',
        ],
        'web.assets_backend': [
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/src/scss/pre_variables.scss',
            'appointment_products/static/src/css/lab_chatter_fix.css',
            'appointment_products/static/src/css/dynamic_results_table.css',
            'appointment_products/static/src/css/lab_result_input.css',
            'appointment_products/static/src/css/lab_ui_improvements.css',
            'appointment_products/static/src/css/lab_timer.css',
            'appointment_products/static/src/css/lab_signature.css',
            'appointment_products/static/src/css/lab_sample_kanban.css',
            'appointment_products/static/src/css/lab_test_flow.css',
            'appointment_products/static/src/scss/lab_test_flow_advanced.scss',
            'appointment_products/static/src/css/lab_test_flow_interactive.css',
            'appointment_products/static/src/js/lab_ui_enhancements.js',
            'appointment_products/static/src/js/lab_test_flow_kanban.js',
            'appointment_products/static/src/js/lab_signature.js',
            #'appointment_products/static/src/js/lab_result_navigation.js',
            #'appointment_products/static/src/scss/lab_dashboard.scss',
            #'appointment_products/static/src/js/lab_dashboard.js',
           # 'appointment_products/static/src/xml/lab_dashboard.xml',
            'appointment_products/static/src/widgets/lab_timer.js',
            'appointment_products/static/src/widgets/lab_timer.xml',
        ],
    },
    'icon': 'appointment_products/static/description/lab_icon.svg',
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',

    'rst_readme': False,
    'demo': [

    ],

    'post_init_hook': 'deactivate_non_masonry',
}