# -*- coding: utf-8 -*-
{
    'name': "SmartLab",
    'summary': "Comprehensive system for managing field service tasks and laboratories with linking products to appointments",
    'description': "System for appointments and field services with dynamic laboratory tests.",
    'author': "Salah Alhjany",
    'website': "https://wa.me/967711778764",
    'category': 'Laboratory/AI',
    'version': '18.0.2.1.0',
    'depends': [
        'appointment', 
        'product', 
        'website_appointment', 
        'website_sale', 
        'website_sale_stock', 
        'web', 
        'sale_management', 
        'phone_validation', 
        'industry_fsm', 
        'industry_fsm_sale', 
        'industry_fsm_report', 
        'stock', 
        'quality',
        'quality_control', 
        'sale_project',
        'timer',
        'mail',
        'base_automation'
    ],
    'data': [

        'security/lab_groups.xml',
        'security/lab_record_rules.xml',
        'security/ir.model.access.csv',
        'security/task_attachment_rules.xml',
        'data/fsm_task_sequence.xml',
        'data/stock_picking_lab_actions.xml',
        'data/brick_test_templates.xml',
        'data/bitumen_test_templates.xml',
        'data/coarse_aggregate_test_templates.xml',
        'data/core_test_templates.xml',
        'data/schmidt_test_templates.xml',
        'views/appointment_product_views.xml',
        'views/appointment_products_templates.xml',
        'views/project_task_signature_views.xml',
        'views/sale_order_question_views.xml',
        'views/portal_task_extra_views.xml',
        'views/product_template_service_views.xml',
        'views/project_task_form_views.xml',
        'views/project_task_stock_done_views.xml',
        'views/report_task_extra_views.xml',
        'views/appointment_config_settings_views.xml',
        'views/stock_move_line_views.xml',
        'views/project_task_buttons.xml',
        'views/stock_picking_buttons.xml',
        'views/stock_picking_lab_notify_views.xml',
        'views/sale_order_buttons.xml',
        'views/stock_picking_report_custom.xml',
        'views/stock_picking_signature_views.xml',
        'views/stock_move_line_signature_views.xml',
        'views/project_task_extra_signatures_views.xml',
        'views/product_labels_simple_enhancement.xml',
        'views/sample_product_config_views.xml',
        'views/sale_order_views_inherit_project_name.xml',
        'views/project_task_attachments_views.xml',
        'views/task_attachment_wizard_views.xml',
        'views/product_subtype_test_plan_wizard_views.xml',
        'views/lab_test_template_views.xml',
        'views/lab_test_criterion_views.xml',
        'views/lab_result_set_views.xml',
        'views/lab_result_signature_views.xml',
        'views/sample_type_views.xml',
        'views/lab_menus.xml',
        'views/quality_lab_integration_views.xml',
        'views/lab_result_dynamic_input_views.xml',
        'views/lab_test_flow_views.xml',
        'views/lab_sample_rule_views.xml',
        'views/lab_sample_views.xml',
        'views/stock_picking_sampling_views.xml',
        'data/lab_sample_sequence.xml',
        'data/lab_result_set_sequence.xml',
        'data/lab_test_flow_sequence.xml',
        'data/lab_sample_rule_data.xml',
        'data/lab_performance_cron.xml',
        'data/lab_notifications.xml',
        'data/field_density_test_templates.xml',
        'data/plr_test_templates.xml',
        'views/lab_dashboard_views.xml',
        'data/ir_sequence_data.xml',
        'data/agg_quality_test_templates.xml',
        'data/proctor_test_templates.xml',
        'views/sample_cube_views.xml',
        'reports/lab_sample_comprehensive_report.xml',
        'data/dynamic_lab_report_actions.xml',
        'views/dynamic_lab_results_template.xml',
        
        'reports/bitumen_standard_report.xml',
        'reports/ignitability_standard_report.xml',
        'reports/brick_standard_report.xml',
        'reports/concrete_core_standard_report.xml',
        'reports/schmidt_hammer_report.xml',
        'reports/field_density_standard_report.xml',
        'reports/plr_standard_report.xml',
        'reports/agg_quality_standard_report.xml',

        'views/project_task_schmidt_views.xml',
        'views/project_task_plr_views.xml',
        'views/schmidt_readings_wizard_views.xml',
        'views/plr_segment_input_wizard_views.xml',
        'data/ignitability_test_templates.xml',
        'data/ll_pl_test_templates.xml',
        'data/cbr_test_templates.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            ('include', 'web._assets_helpers'),
            ('include', 'web._assets_frontend_helpers'),
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/jquery/jquery.js',
            'appointment_products/static/src/js/appointment_products.js',
            'appointment_products/static/src/js/appointment_cart.js',
        ],
        'web.assets_backend': [
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/src/scss/pre_variables.scss',
            'appointment_products/static/src/css/lab_chatter_fix.css',
            'appointment_products/static/src/css/dynamic_results_table.css',
            'appointment_products/static/src/css/lab_result_input.css',
            'appointment_products/static/src/css/lab_ui_improvements.css',
            'appointment_products/static/src/css/lab_timer.css',
            'appointment_products/static/src/css/lab_signature.css',
            'appointment_products/static/src/css/lab_sample_kanban.css',
            'appointment_products/static/src/css/lab_test_flow.css',
            'appointment_products/static/src/scss/lab_test_flow_advanced.scss',
            'appointment_products/static/src/css/lab_test_flow_interactive.css',
            'appointment_products/static/src/js/lab_ui_enhancements.js',
            'appointment_products/static/src/js/lab_test_flow_kanban.js',
            'appointment_products/static/src/js/lab_signature.js',
            'appointment_products/static/src/js/lab_result_navigation.js',
            'appointment_products/static/src/scss/lab_dashboard.scss',
            'appointment_products/static/src/js/lab_dashboard.js',
            'appointment_products/static/src/xml/lab_dashboard.xml',
            'appointment_products/static/src/widgets/lab_timer.js',
            'appointment_products/static/src/widgets/lab_timer.xml',
            # Charts widget (uses Chart.js; the widget can lazy-load CDN if missing)
            'appointment_products/static/src/widgets/lab_charts.js',
            'appointment_products/static/src/xml/lab_charts.xml',
        ],
        'web.report_assets_common': [
            'appointment_products/static/src/css/report_fonts.css',
        ],
    },
    'icon': 'appointment_products/static/description/lab_icon.png',
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'OPL-1',

    'rst_readme': False,
    'demo': [

    ],

    'post_init_hook': 'deactivate_non_masonry',
}
