# -*- coding: utf-8 -*-
{
    'name': 'Appointment Financial Voucher Report',
    'summary': 'Custom financial voucher report for field service/appointments',
    'version': '1.0.0',
    'category': 'Laboratory',
    'author': "Salah Alhjany",
    'website': "https://wa.me/967711778764",
    'license': 'OEEL-1',
    'depends': [
        'account',
        'sale',
        'sale_management',
        'project',
        'sale_project',
        'industry_fsm',
        'appointment_products',
        'custom_report_layout',
    ],
    'data': [
        'security/ir.model.access.csv',
        'reports/financial_voucher_report.xml',
        'views/forms_summary_wizard.xml',
        'reports/forms_summary_report.xml',
        'reports/form_intake_report.xml',
        'reports/settlement_summary_report.xml',
        'reports/payment_receipt_duplicate_report.xml',
    ],
    'assets': {},
    'installable': True,
    'application': False,
}
